# Generated by Django 3.1.2 on 2024-08-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='data',
            field=models.CharField(max_length=255),
        ),
    ]
